// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMbClkXN9PlFztJdKh-R1I0BaRNKn1Z5Y',
    appId: '1:82065730254:web:615ac6813be6685b8ebe9f',
    messagingSenderId: '82065730254',
    projectId: 'currency-converter-a6f07',
    authDomain: 'currency-converter-a6f07.firebaseapp.com',
    storageBucket: 'currency-converter-a6f07.firebasestorage.app',
    measurementId: 'G-DFG7XPZCNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqyP46rYZNjrWQeE3ebdhDdy1dNebp_Bg',
    appId: '1:82065730254:android:39ae8f41fd1a56a08ebe9f',
    messagingSenderId: '82065730254',
    projectId: 'currency-converter-a6f07',
    storageBucket: 'currency-converter-a6f07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDULfopG2DQ6WB5S0GylwgKNRH5zT88ypI',
    appId: '1:82065730254:ios:bac5967ab4c960328ebe9f',
    messagingSenderId: '82065730254',
    projectId: 'currency-converter-a6f07',
    storageBucket: 'currency-converter-a6f07.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDULfopG2DQ6WB5S0GylwgKNRH5zT88ypI',
    appId: '1:82065730254:ios:bac5967ab4c960328ebe9f',
    messagingSenderId: '82065730254',
    projectId: 'currency-converter-a6f07',
    storageBucket: 'currency-converter-a6f07.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMbClkXN9PlFztJdKh-R1I0BaRNKn1Z5Y',
    appId: '1:82065730254:web:08c7839fdde182318ebe9f',
    messagingSenderId: '82065730254',
    projectId: 'currency-converter-a6f07',
    authDomain: 'currency-converter-a6f07.firebaseapp.com',
    storageBucket: 'currency-converter-a6f07.firebasestorage.app',
    measurementId: 'G-VQYY2ZQ97N',
  );
}
